repositories = ["chef/mixlib-cli", "chef/mixlib-log", "chef/mixlib-config",
                "chef/mixlib-authentication", "chef/mixlib-authorization",
                "chef/mixlib-shellout", "chef/mixlib-versioning", "chef/mixlib-archive",
                "chef/ohai", "chef/cheffish", "chef/chef-zero", "chef/chefstyle",
                "chef/cookbook-omnifetch", "chef/rs-chef-api"]

[[label]]
color = "e11d21"
mappings = [ "Bug", "bug" ]
name = "Type: Bug"

[[label]]
color = "ededed"
delete = true
name = "CLA Verified"

[[label]]
color = "ededed"
delete = true
name = "Delivery Change Created"

[[label]]
color = "c7def8"
name = "Type: Documentation"
mappings = ["Documentation", "documentation"]

[[label]]
color = "bfe5bf"
name = "Type: Jump In"
mappings = ["Easy", "hacktoberfest", "Hacktoberfest", "help wanted", "Help Wanted"]

[[label]]
color = "009800"
name = "Type: Enhancement"
mappings = ["Enhancement", "enhancement", "Improvement", "New Feature", "Feature"]

[[label]]
color = "cccccc"
name = "Status: Duplicate"
mappings = [ "duplicate", "Duplicate" ]

[[label]]
color = "bfd4f2"
name = "Expeditor: Exclude From Changelog"
mappings = ["Changelog: Skip Update"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip All"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Build"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Version Bump"
mappings = ["Version: Skip Bump"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Bump Minor Version"
mappings = ["Version: Bump Minor"]

[[label]]
color = "5319e7"
name = "Status: Finish for Merge"
mappings = ["Finish for Merge"]

[[label]]
color = "eb6420"
name = "Priority: Critical"
mappings = ["High Priority"]

[[label]]
color = "0052cc"
name = "Status: Incomplete"
mappings = ["Incomplete Contribution", "Developing"]

[[label]]
color = "eb6420"
name = "Priority: Low"
mappings = ["Low Priority"]

[[label]]
color = "eb6420"
name = "Priority: Medium"
mappings = ["Medium Priority"]

[[label]]
color = "0052cc"
name = "Status: Pending Maintainer Review"
mappings = ["Pending Maintainer Review", "Review Required", "Reviewing"]

[[label]]
color = "5319e7"
name = "Status: Ready for Merge"
mappings = ["Ready for Merge"]

[[label]]
color = "e11d21"
name = "Type: Regression"
mappings = ["Regression"]

[[label]]
color = "ededed"
delete = true
name = "Signed CLA"

[[label]]
name = "wontfix"
delete = true

[[label]]
name = "invalid"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Attack List"
delete = true

[[label]]
name = "Tech Cleanup"
delete = true

[[label]]
name = "Needs Action"
delete = true

[[label]]
color = "0052cc"
name = "Status: Pending Contributor Response"
mappings = ["Waiting for Contributor Response", "Waiting", "Feedback Requested", "waitingresponse"]

[[milestones]]
description = "Bucket to pull issues from for next minor. These issues should be fixable without needing a *major* version bump per semver; they're unlikely to cause a compatibility break or an API change."
name = "Accepted Minor"
state = "open"

[[milestones]]
description = "Bucket for breaking changes to pull for next Major"
name = "Accepted Major"
state = "open"

[[milestones]]
description = "Triaged issues that are low priority and are not being worked on."
name = "Help Wanted"
state = "open"

[[milestones]]
description = "Documentation updates and fixes"
name = "Documentation"
state = "open"

[[milestones]]
description = "Bucket for issues that are discussions or bikesheds and which are not yet directly actionable but also not yet closable, and are not appropriate to assign to either a major or minor release milestone.\r\n"
name = "Discussion"
state = "open"
